import tkinter as tk
root=tk.Tk()
root.geometry("600x400")
root.title("demo")
button_1=tk.Button(root,text="click me",fg="blue",relief="groove")
button_1.pack(side="right")
button_2=tk.Button(root,text="BUTTON",fg="blue")
button_2.pack(after=button_1,pady=50)
button_3=tk.Button(root,text="press here")
button_3.pack(anchor='w',ipady=50)
entry_1=tk.Entry(root,width=10,bd=5)
entry_1.pack()
text_1=tk.Text(root)
text_1.pack()
label_1=tk.Label(root,text="username")
label_1.pack()
canvas_1=tk.Canvas(root,bg="red",width=100,height=100)
canvas_1.pack()
checkbutton_1=tk.Checkbutton(root,bg="yellow",activebackground="green",activeforeground="red")
checkbutton_1.pack()
radiobutton_1=tk.Radiobutton(root,bg="grey")
radiobutton_1.pack()
frame_1=tk.Frame(root)
frame_1.pack()
message_1=tk.Message(root,bg="blue",width=60)
message_1.pack()
scrollbar_1=tk.Scrollbar()
scrollbar_1.pack()
scale_1=tk.Scale()
scale_1.pack()
root.mainloop()